import {
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  BarChart,
  Bell,
  BookIcon,
  BookImageIcon,
  BookOpenText,
  Brain,
  Calendar,
  CalendarSearchIcon,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRightIcon,
  ChevronsUpDown,
  Circle,
  Clock,
  CoinsIcon,
  CopyIcon,
  CreditCard,
  DatabaseZapIcon,
  DollarSign,
  File,
  FileText,
  Folder,
  GlobeIcon,
  HelpCircle,
  HospitalIcon,
  Image as ImageIcon,
  Inbox,
  Laptop,
  LineChartIcon,
  Loader2,
  LockIcon,
  LogOut,
  LucideIcon,
  MailIcon,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MoonStar,
  MoreHorizontal,
  MoreVertical,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  PuzzleIcon,
  SaveIcon,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareTerminal,
  Stethoscope,
  SunMedium,
  ToggleRightIcon,
  Trash,
  TrendingDown,
  TrendingUp,
  UserCircleIcon,
  UserCogIcon,
  UserPlus,
  Users,
  X,
  ZapIcon,
} from "lucide-react"
import { FaDiscord, FaGithub, FaGoogle } from "react-icons/fa"
import { FaXTwitter } from "react-icons/fa6"
import {
  MdOutlineDescription,
  MdOutlineIntegrationInstructions,
  MdOutlineMemory,
} from "react-icons/md"
import { SiPrisma } from "react-icons/si"

export type Icon = LucideIcon

function LogoIcon({ className }: { className?: string }) {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 32 32"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <path
        d="M16 2C8.268 2 2 8.268 2 16s6.268 14 14 14 14-6.268 14-14S23.732 2 16 2z"
        fill="#6366F1"
      />
      <path
        d="M22 12.5l-8.5 8.5L9 16.5"
        stroke="white"
        strokeWidth="3"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export const Icons = {
  logo: LogoIcon,
  logoLucide: ChevronsRightIcon,
  close: X,
  up: ArrowUp,
  down: ArrowDown,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  twitter: FaXTwitter,
  check: Check,
  orderbook: BookOpenText,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  discord: FaDiscord,
  github: FaGithub,
  memory: MdOutlineMemory,
  integrationInstructions: MdOutlineIntegrationInstructions,
  description: MdOutlineDescription,
  lock: LockIcon,
  puzzle: PuzzleIcon,
  globe: GlobeIcon,
  databaseZap: DatabaseZapIcon,
  blog: BookImageIcon,
  graph: LineChartIcon,
  prisma: SiPrisma,
  zap: ZapIcon,
  copy: CopyIcon,
  toggleRight: ToggleRightIcon,
  creditCard: CreditCard,
  calendar: Calendar,
  barChart: BarChart,
  clock: Clock,
  brain: Brain,
  menu: Menu,
  document: BookIcon,
  folder: Folder,
  more: MoreHorizontal,
  badgeCheck: BadgeCheck,
  bell: Bell,
  logOut: LogOut,
  sparkles: Sparkles,
  studio: SquareTerminal,
  register: UserPlus,
  appointment: CalendarSearchIcon,
  coins: CoinsIcon,
  location: MapPin,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  dollarSign: DollarSign,
  users: Users,
  inbox: Inbox,
  arrowUpDown: ArrowUpDown,
  circle: Circle,
  helpCircle: HelpCircle,
  shield: Shield,
  therapist: Stethoscope,
  staff: Users,
  pending: Loader2,
  approved: Check,
  rejected: X,
  contacted: MailIcon,
  demoScheduled: CalendarSearchIcon,
  demoCompleted: Check,
  contractSigned: FileText,
  onboarding: UserCogIcon,
  joined: UserPlus,
  save: SaveIcon,
  question: HelpCircle,
  google: FaGoogle,
  clinic: HospitalIcon,
  edit: PencilIcon,
  userPlus: UserPlus,
  leave: LogOut,
  chevronDown: ChevronDown,
  moonStar: MoonStar,
}
